import Service from "components/layouts/Service";
import Cities from "components/layouts/Cities";
import ExploreMyCity from "components/layouts/ExploreMyCity";
import Footer from "components/layouts/Footer";
import Goal from "components/layouts/Goal";
import Hero from "components/layouts/Hero";
import LinkdinGroup from "components/layouts/LinkdinGroup";
import Navbar from "components/layouts/Navbar";
import Partners from "components/layouts/Partners";
import Team from "components/layouts/Team";
import WhyTrustUs from "components/layouts/WhyTrustUs";
import CallToAction from "components/layouts/CallToAction";
import HowItWorks from "components/layouts/HowItWorks";
import Head from "next/head";
import { PageContainer } from "styles/globalStyles";

export default function Home() {
	return (
		<PageContainer>
			<Head>
				<title>Ganbatte</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />
			<Hero />
			<Cities />
			<Service />
			<CallToAction />
			<HowItWorks />
			<Team />
			<Goal />
			<WhyTrustUs />
			<ExploreMyCity />
			<Partners />
			<LinkdinGroup />
			<Footer />
		</PageContainer>
	);
}
