// MOBILE BREAKPOINTS START
export const MOBILE_SCREEN_1 = "575px";
export const MOBILE_SCREEN_2 = "360px";
// MOBILE BREAKPOINTS END

// TABLET BREAKPOINTS START
export const TABLET_SCREEN_1 = "760";
// TABLET BREAKPOINTS END

// DESKTOP BREAKPOINTS START
export const DESKTOP_SCREEN_1 = "1000px";
export const DESKTOP_SCREEN_2 = "1200px";
// DESKTOP BREAKPOINTS END
